### ISSUE TITLE
RocCheckerConfig references an invalid Table: precip. Skipping config.

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#116]
```
ERROR 2017-03-21 01:37:00,035 9881 [DefaultQuartzScheduler_Worker-5] RocChecker: Roc Checker Config: RocCheckerConfig [table=precip, quality=G, startHours=6, endHours=0, rocCheckerConstraints=RocCheckerConstraints [pes={PC}]] references an invalid Table: precip. Skipping config.

```

**Comment by mjames-upc** [comment]
from http://www.wdtb.noaa.gov/buildTraining/awips16-4-1/overview/presentation_content/external_files/AWP.RLSN.OB16.4.1_Final.pdf pp A-134

> Release Note: Omaha #5590, #5699
A Java version of Roc Checker has been created. The hydroapps version of Roc Checker
required command-line arguments hard-coded into one of the hydroapps shell scripts to indicate
which hydro database tables to run the check against. For the Java application, the tables to
check can be configured using a new localization file: RocChecker.xml. The Java version of Roc
Checker has been setup to run in parallel with its hydroapps counterpart like the Java version of
biasmesgen has. It will store data that is generated in a separate directory and execute an
automatic comparison. The Java application will log all activity to the new edex-ingest-mpe log.

**Comment by mjames-upc** [comment]
ROC as in Rate of Change (rate-of-change quality control operation)

**Comment by bkowaluno** [comment]
As the AWIPS II developer that originally started working on the Rate of Change Java to C++ application conversion, the log message can be ignored. There is also a valid aspect of the original configuration that references a hydrology table that actually exists and completes processing as expected. The long-term objective was to complete an implementation that allowed a full comparison between the old, legacy C++ code and the new Java code. Then, a final cleanup would be completed prior to the full transition to the Java implementation. https://www.linkedin.com/in/bryan-kowal-abb39019
