### ISSUE TITLE
EDEX rpm install error - rpm unavailable

### ISSUE THREAD

**Issue by pjcioffi** [Unidata/awips2#130]
While running **./installEDEX.sh**:

**Downloading packages:
Delta RPMs reduced 1.1 M of updates to 474 k (58% saved)
http://www.unidata.ucar.edu/repos/yum/awips2-el7/noarch/awips2-maps-database-16.2.2-2.el7.centos.noarch.rpm: [Errno 14] HTTP Error 403 - Forbidden
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/solutions/69319

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/

Error downloading packages:
  awips2-maps-database-16.2.2-2.el7.centos.noarch: [Errno 256] No more mirrors to try.

Done...**

Apologies if this is already covered. Could not find a similar issue.

**Comment by mjames-upc** [comment]
@pjcioffi from what country are you trying to download this package (and others)?  There may be some IP address restrictions due to some of our server getting too many repeated requests.

**Comment by pjcioffi** [comment]
@mjames-upc  I was trying to download it from the installEDEX.sh script default. I believe it uses: http://www.unidata.ucar.edu/repos/yum/awips2/noarch/ or http://www.unidata.ucar.edu/repos/yum/awips2-el7/noarch/

**Comment by mjames-upc** [comment]
@pjcioffi from what country?

**Comment by mjames-upc** [comment]
are you able to wget http://www.unidata.ucar.edu/repos/yum/awips2-el7/noarch/awips2-maps-database-16.2.2-2.el7.centos.noarch.rpm ?

**Comment by pjcioffi** [comment]
@mjames-upc California, USA (via Comcast-Xfinity). 

No, I am not able to wget that address. "Error 403- Forbidden".

**Comment by mjames-upc** [comment]
Aha, it was a permission error on the web server.  Try again please.

**Comment by pjcioffi** [comment]
That did the trick. Thank you.
