### ISSUE TITLE
Warn Gen Issue on Mac

### ISSUE THREAD

**Issue by cristoph15** [Unidata/awips2#158]
Warn gen says I need to have workstation host name. Can someone help me??

**Comment by mjames-upc** [comment]
In CAVE > Preferences you should have a Text Workstation server option which should be set to "localhost".

**Comment by cristoph15** [comment]
I got it to work. I was able to use my localhost and then it worked. I do thank you for the advice. I hope you have a great rest of your day, wherever you are in the world.

**Comment by cristoph15** [comment]
The chat can be closed now, by the owners of the issue page. I really appreciate the help.
