### ISSUE TITLE
WarnGen issue on Linux/Windows with 16.2.2

### ISSUE THREAD

**Issue by airbusman5514** [Unidata/awips2#159]
Does WarnGen let us create text on Windows and Linux for Version 16.2.2? If so, how do I do it? Currently, when I hit create text the text window doesn't come up.

**Comment by cristoph15** [comment]
Sorry for the late response. You go to tools, text window. In the most left place to type, enter WRKWG1. Tell if you get a warning.

**Comment by cristoph15** [comment]
![wrkwg1](https://cloud.githubusercontent.com/assets/17783449/25876353/9b1863fe-34ea-11e7-9a3b-2773e960e5c9.gif)

**Comment by airbusman5514** [comment]
It halfway works. I get a warning, but it's a severe thunderstorm warning when I was trying to create a tornado emergency, and it only includes two of the counties I tried to include in the warning, which were Hutchinson, Roberts, Carson, and Gray Counties. The time is also off by about an hour. A link to a screenshot is attached below.

http://prntscr.com/f611de

EDIT: This seems to be the case with every WFO. It doesn't come up with a current warning, but a dated warning for about a month previous, and only severe thunderstorm warnings. Maybe it has something to do with me using the Unidata EDEX sever.

**Comment by cristoph15** [comment]
@mjames-upc, I was able to help some of the way. Do you know how to fully fix the issue?

**Comment by cristoph15** [comment]
@mjames-upc, Are you still alive. I need some help helping somebody else.

**Comment by mjames-upc** [comment]
Warngen/TextWS has been fixed for practice use in the upcoming 17.1.1 release.

**Comment by airbusman5514** [comment]
Whee! When will the 17.1.1 release be out?

Kyle
