### ISSUE TITLE
WarnGen and Pathcast

### ISSUE THREAD

**Issue by airbusman5514** [Unidata/awips2#189]
Sometimes when issuing warnings, for some WFOs Pathcast works, but others it gives what looks like lines of Java code. It happens with a lot of eastern WFOs like IND and ILN, etc.

![screenshot-text warngen indsvrind now editing](https://user-images.githubusercontent.com/28398677/29195622-4a57fa68-7de4-11e7-9415-fc6ef193f5cb.png)

Any ideas how to fix?

**Comment by mjames-upc** [comment]
This is not a software issue.  Note the IMPACT message.  Probably the case that the warning was not generated correctly. Worth consulting the warngen docs for exactly what you're trying to do.
