### ISSUE TITLE
Debian/Ubuntu Support [New Feature]

### ISSUE THREAD

**Issue by four43** [Unidata/awips2#209]
Hey all,

Any interest in building a .deb package for Debian/Ubuntu Linux OSes?

It would convenient for us, but before anyone puts in the effort any other interest?

**Comment by mjames-upc** [comment]
Yes I plan to attempt an Ubuntu CI build as soon as the next stable release is out.  No promises, but hopefully we can get it working.

**Comment by four43** [comment]
Hey that's great news, thanks!
