### ISSUE TITLE
17.1.1-5 (macOS): No upper air data in nsharp

### ISSUE THREAD

**Issue by jaredwsmith** [Unidata/awips2#212]
Since upgrading to 17.1.1-5 and pointing to EDEX servers running the same, I am no longer able to see RAOB soundings in nsharp. I see that data is still flowing to the server in the entries under the Upper Air menu, but when I try to load in any of those soundings, they do not appear. Notably, model soundings as well as NUCAPS continue to function properly. I've tried both against the Unidata cloud server as well as a private EDEX.

**Comment by mjames-upc** [comment]
Thanks for letting me know.  I can confirm this when connected to edex-cloud.unidata.ucar.edu while NSHARP soundings load as expected on my development servers.  

Unrelated to this, but relevant, w will be moving edex-cloud to a new server later today which is capable of ingesting much more data.  UAIR soundings are confirmed working on this new server, so once it's live you will be able to load profiles again, and I can go investigate what's going on with the old server.

**Comment by klatteri** [comment]
I am still having this issue for my EDEX server running with on Linux CAVE (CentOS 6.6)

**Comment by jaredwsmith** [comment]
Worth noting that I'm now seeing this issue with model soundings loaded from the Volume Browser as well. Was unable to get it to work even on edex-cloud.
