### ISSUE TITLE
Mac cave

### ISSUE THREAD

**Issue by cag20** [Unidata/awips2#220]
My cave wont log me in and i got a nother computer its on windows its the same cave software but my windows is taking for ever to load but i dont have centos v6.9 but like i said in the top part of the message its not leting me inhow do o fix than & the windows. version is taking for ever so how do i fix that

**Comment by mjames-upc** [comment]
@cag20 it may be that the server was down during the period you were trying to connect.  I recently redeployed the edex-cloud server to fix some downtime problems we've been encountering.  Can you connect today?
