### ISSUE TITLE
WarnGen doesn't seem to work (Windows)

### ISSUE THREAD

**Issue by FDDTheLucario** [Unidata/awips2#225]
So I'm trying to use Warngen... and it doesn't work. When I open it, the Text Workstation doesn't open, and when I click on "Create Text", it says the standard "Generating product" box and that's it. Why is this?

**Comment by FrostTheFox** [comment]
The installable version for Windows is based on an older release and doesn't include some changes to WarnGen that fix these issues.

**Comment by mjames-upc** [comment]
Yup, the Windows client is old and provided as an alternative to nothing.  I'm updating to 18.1.1 and when that release is ready for Linux and macOS I will attempt another Windows build, crossing my fingers that it works this time with updates to Eclipse and PyDEV.
