### ISSUE TITLE
Model data wont load

### ISSUE THREAD

**Issue by weather483** [Unidata/awips2#253]
Hi,

My model data wont work  and I was trying to use the HRRR model and I would like an image to show up for example:
![unnamed](https://user-images.githubusercontent.com/33179389/44301543-c2d95180-a2e6-11e8-94b0-9ebbcc8a8860.png)
and I purchased a license from allisonhouse and they told me to post here.

Thanks,

Greg Metzger

**Comment by mjames-upc** [comment]
Unidata is an educational non-profit and will not support use of Allison House software.
