### ISSUE TITLE
version numbers broken on macOS

### ISSUE THREAD

**Issue by core-code** [Unidata/awips2#255]
i've downloaded Version '18.1.1' but when selecting it in the Finder and using 'Get Info' it shows Version 'Eclipse 3.6 for Mac OS X, Copyright IBM Corp. and others 2002, 2010. All rights reserved.'

i think the
CFBundleVersion
and 
CFShortVersionString
entries in your Info.plist file should be adapted to reflect that this is
1.) not ECLIPSE but AWIPS
 2.) version 18.1.1 and not version 3.6

**Comment by mjames-upc** [comment]
Got this. Thanks for letting me know.  New DMG available later today.

**Comment by core-code** [comment]
awesome, thanks!

**Comment by core-code** [comment]
any idea where the updated DMG is available for download?

also, dumb question but why does the homepage offer version 17.1.1 while the documentation page offers version 18.1.1 for download?

**Comment by mjames-upc** [comment]
https://www.unidata.ucar.edu/downloads/awips2/awips2-cave-18.1.1-1.dmg is the latest

you're seeing different versions in documentation because the release is slowly happening this week.

**Comment by core-code** [comment]
thanks ;)
