### ISSUE TITLE
18.1.1-1: No volume browser available in menu

### ISSUE THREAD

**Issue by jaredwsmith** [Unidata/awips2#258]
I noticed after installing the 18.1.1-1 release via RPM that the Volume Browser is no longer available. Confirmed by installing the Mac DMG as well. Is this a temporary issue?

**Comment by mjames-upc** [comment]
Resolved. macOS and Windows clients have been updated to include the Volume Browser.  Linux clients will be updated shortly.

**Comment by jaredwsmith** [comment]
I sit corrected -- all is well with today's release. Closing out!
