### ISSUE TITLE
AWIPS 17.1.1 Grid Data Null Pointer

### ISSUE THREAD

**Issue by ghost** [Unidata/awips2#266]
Hello,

I'm using the 17.1.1 version (seems to be performing better on my computer than 18.1.1) on Windows 10 with AllisonHouse's EDEX server. It's been working fine and continues to work on my other computer but on my main one, I'm unable to load any grid data or radar data. I can load the satellite data and that's about it. I've uninstalled both AWIPS and Java several times to try to resolve the issue with no luck. Everytime I try load data via the product browser I'm given a null pointer exception.

Alert View Error: [awips_error.txt](https://github.com/Unidata/awips2/files/2461378/awips_error.txt)

![2018-10-09](https://user-images.githubusercontent.com/21148305/46684535-166a6c00-cbc1-11e8-9f76-7f5ebdc22cbf.png)

**Comment by mjames-upc** [comment]
I believe this is due to the grid names being different between Unidata CAVE and the non-Unidata server you're using, and/or differences in how the product browser populates by datatype. I do not have a solution for you since I do not support non-Unidata EDEX servers.

**Comment by ghost** [comment]
I ran AWIPS on another computer and didn’t have the issue. It’s something occurring on this machine specifically, I was hoping you might have some idea as to why? I’ve reinstalled AWIPS and Java several times with no success.
