### ISSUE TITLE
Map only shows in 1/4 of screen

### ISSUE THREAD

**Issue by noahsevcik** [Unidata/awips2#270]
When I open up CAVE, I get the screen displayed in the picture below. I know the program and have tried to look for settings to adjust and haven't found them (no, zooming does not work). The map only displays in the bottom left corner of my screen. I'm assuming it's my graphics card (GTX 1080), but I don't quite know what the problem is or how to solve it.
![awipszoomed](https://user-images.githubusercontent.com/45643419/49551941-f69caf00-f8b6-11e8-9266-7a1ec59a979c.PNG)
![awipsproblem](https://user-images.githubusercontent.com/45643419/49551942-f69caf00-f8b6-11e8-914f-a9dcc9fc8263.PNG)

**Comment by mjames-upc** [comment]
* What version of linux is this?
* What version of CAVE?
* If you remove ~/caveData and restart does it happen again?
* Are you able to run "File -> New Projection" and create a new map that fills the editor as expected, or is every new projection confined to the lower-left?

**Comment by noahsevcik** [comment]
I'm running windows 10 x64 1803
I'm running the latest version of CAVE
Deleting the files does nothing
Creating a new projection does nothing

**Comment by jaredwsmith** [comment]
I have seen this before on Windows machines using HiDPI resolutions. You should be able to right-click the shortcut, go to Properties, and then the Compatibility tab where you can enable scaling for CAVE. _In theory_, this should resolve the issue. I'm not sure about practice, though; I don't have access to a Windows 10 machine pumping enough pixels to verify this first-hand.

**Comment by noahsevcik** [comment]
Jared,
Thanks for the advice, but it didn't work. It seemed to work when I
switched my display's resolution to 1920x1080, but my display is in 4k.
This'll have to do for now!

**Comment by mjames-upc** [comment]
Working with another user we have found a solution to this.

* Right-click on the CAVE.exe (or shortcut) icon, select Properties
* Select the Compatibility tab 
* Click "Change High DPI Settings" 
* At the bottom enable "Override High DPI scaling behavior"
* Change the dropdown from Application to System
