### ISSUE TITLE
Extra dependencies required for windows installation

### ISSUE THREAD

**Issue by CaptainStabs** [Unidata/awips2#295]
Windows 10 x64, JDK 14.0.2, python3, jep 3.8.2 (as mentioned in the docs), NumPy 1.15.1, AWIPS Release 18.1.1-7, March 25, 2019

The JDK folder must be put into the miniconda3 folder, and the `JAVA_HOME` variable be set to its location (in my case `C:\user\miniconda3\jdk-14.0.2`)

Missing dependency in the docs:  Microsoft Visual C++ 14.1 (Required by jep)

This is an issue with http://unidata.github.io/awips2/install/install-cave/#windows

**Comment by rszasz** [comment]
after installing the build tools, use the following before pip install jep==3.8.2 (for x64 arch)

set MSSdk=1 
set DISTUTILS_USE_SDK=1  
"\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
