### ISSUE TITLE
Error installing EDEX

### ISSUE THREAD

**Issue by sloohe10** [Unidata/awips2#301]
Hello,

I am trying to install EDEX on my laptop using virtualbox with CentOS Linux release 8.2.2004.
I want to send my data to EDEX and then use cave to view my WRF forecast on Cheyenne.
I followed the instructions from:
http://unidata.github.io/awips2/install/install-edex/

I get an error when I try run this command:
/usr/bin/edex setup

error reading information on service qpidd: No such file or directory
error reading information on service qpidd: No such file or directory
error reading information on service edex_camel: No such file or directory
error reading information on service edex_camel: No such file or directory
[Error] ** /awips2/edex/bin/setup.env not found.
Exiting

thank you

**Comment by srcarter3** [comment]
Hi there,

I believe the main problem you're running into is the OS version.  As stated in the general requirements: http://unidata.github.io/awips2/install/install-edex/#system-requirements, our EDEX is only supported for CentOS/Redhat 7 currently.
If I'm understanding you correctly, you are creating a Linux Virtual Machine in Virtualbox, and are using CentOS 8 right now.  Please try creating a CentOS 7 machine and installing EDEX on that.
Thank you.

**Comment by sloohe10** [comment]
Hello srcarter3,

thank you for your help

I think now it is installed, but I am not sure if the ldm is installed correctly or not.
I attached the log file of the installation. I would be grateful if you could look it and check if everything is ok. 

And now when I run /usr/bin/edex setup
I get is message:
 
You do not have enough privileges to perform this operation.
You do not have enough privileges to perform this operation.
You do not have enough privileges to perform this operation.
You do not have enough privileges to perform this operation.
You do not have enough privileges to perform this operation.
You do not have enough privileges to perform this operation.
You do not have enough privileges to perform this operation.
You do not have enough privileges to perform this operation.
Password: 




best regards

[EDEX.logfile.txt](https://github.com/Unidata/awips2/files/5588381/EDEX.logfile.txt)

**Comment by srcarter3** [comment]
Hi there,

Have you tried running the command with sudo?
`sudo edex setup`

**Comment by sloohe10** [comment]
Hello Srcarter,

yes, I tried it with sudo and I get this message:

[sa7@localhost ~]$ sudo edex setup
[sudo] password for sa7: 

20201124T201654.353183Z               regutil[3006]             backend.c:fileLock() ERROR Permission denied
20201124T201654.353537Z               regutil[3006]             backend.c:fileLock() ERROR Couldn't open file "/awips2/ldm/etc/registry.xml" for writing
20201124T201654.353588Z               regutil[3006]                registry.c:sync() ERROR Couldn't synchronize node "/"
20201124T201654.353900Z               regutil[3006]       registry.c:reg_putString() ERROR Couldn't store value "localhost.localdomain" in parameter "/hostname"
[edex] EDEX IP and Hostname Setup
[edit] localhost.localdomain added to /awips2/edex/bin/setup.env
       File backed up to /awips2/edex/bin/setup.env.setup_20201124
[sa7@localhost ~]$

**Comment by srcarter3** [comment]
Hi there,

A few things, first we'd like to make sure the LDM installed correctly. 
Can you confirm you have gcc-c++ installed?
```
rpm -qa | grep gcc-c++
```

Can you also list the contents of the ldm directory?
```
ls -l /awips2/ldm
```

And lastly, it might be helpful to run the `edex` commands as user 'awips'.  So try switching to that user first before running the setup command:
```
sudo su - awips  
edex setup
```

Thanks.

**Comment by sloohe10** [comment]
Hi Srcarter,
here is is what I get when I run these commands:
[sa7@localhost ~]$ rpm -qa | grep gcc-c++
[sa7@localhost ~]$ ls -l /awips2/ldm
total 6136
lrwxrwxrwx. 1 root  root         11 Nov 23 23:54 bin -> runtime/bin
drwxr-xr-x. 2 awips awips       143 Mar 20  2019 decoders
drwxr-xr-x. 2 awips awips       156 Mar 20  2019 etc
lrwxrwxrwx. 1 root  root         15 Nov 23 23:54 include -> runtime/include
drwxr-xr-x. 7 root  root         67 Nov 23 23:53 ldm-6.13.10
-rw-r--r--. 1 root  root    6281237 Nov 23 23:52 ldm-6.13.10.tar.gz
lrwxrwxrwx. 1 root  root         11 Nov 23 23:54 lib -> runtime/lib
lrwxrwxrwx. 1 root  root         11 Nov 23 23:54 runtime -> ldm-6.13.10
lrwxrwxrwx. 1 root  root         13 Nov 23 23:54 share -> runtime/share
drwxr-xr-x. 2 awips fxalpha     104 Nov 23 23:52 SOURCES
lrwxrwxrwx. 1 root  root         11 Nov 23 23:54 src -> runtime/src
drwxr-xr-x. 5 root  root         44 Nov 23 23:54 var
[sa7@localhost ~]$ sudo su - awips  
[sudo] password for sa7: 
Last login: Tue Nov 24 13:28:33 MST 2020 on pts/0
[awips@localhost ~]$ edex setup

You do not have enough privileges to perform this operation.
You do not have enough privileges to perform this operation.
You do not have enough privileges to perform this operation.
You do not have enough privileges to perform this operation.
You do not have enough privileges to perform this operation.
You do not have enough privileges to perform this operation.
You do not have enough privileges to perform this operation.
You do not have enough privileges to perform this operation.
Password: 

I do not think that I have gcc-c++ installed
thank you

**Comment by srcarter3** [comment]
Hi there,

Okay, I think you are correct and gcc-c++ is not installed.  In that case:

Install it (as root):
```
yum install gcc-c++
```

Then, try and remove the awips2-ldm rpm manually (as root):
```
yum remove awips2-ldm
```

Delete the ldm directory if it still exists:
```
rm -rf /awips2/ldm
```

Then try installing ldm again (as root):
```
yum clean all ; yum install awips2-ldm
```

And then I believe you should be able to run the setup, if it doesn't work with just `edex setup` try again with `sudo edex setup`, and then let me know how that goes.

Thanks.

**Comment by sloohe10** [comment]
Hi,
I got an error in running the following command:

[sa7@localhost ~]$ sudo yum clean all ; yum install awips2-ldm
Loaded plugins: fastestmirror, langpacks
Cleaning repos: awips2repo base epel extras updates
Cleaning up list of fastest mirrors
There was a problem importing one of the Python modules
required to run yum. The error leading to this problem was:

   No module named yum

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
2.7.13 (default, Nov 15 2017, 23:42:24) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

If you cannot solve this problem yourself, please go to 
the yum faq at:
  http://yum.baseurl.org/wiki/Faq
  

[sa7@localhost ~]$ 

thank you

**Comment by srcarter3** [comment]
You need to make sure you're running those commands as root.
```
sudo su - root
```

**Comment by sloohe10** [comment]
thank you
I got the following message. please the the attachment
thank you so much
[ldm.logfle.txt](https://github.com/Unidata/awips2/files/5592864/ldm.logfle.txt)

**Comment by srcarter3** [comment]
Great, glad to help!

And thank you for opening this issue, we have made a change to our documentation and added the gcc-c++ dependency to the System Requirements on our Edex Installation page: 
http://unidata.github.io/awips2/install/install-edex/#system-requirements

So hopefully, other users won't have the same problem you experienced.
Thanks.
