### ISSUE TITLE
password for awips: 

### ISSUE THREAD

**Issue by sloohe10** [Unidata/awips2#302]
Hello,
I have installed EDEX, but I have a problem in setting it up.
I get the following message:

[root@localhost ~]# sudo su - awips
Last login: Tue Nov 24 16:50:36 MST 2020 on pts/0
[awips@localhost ~]$ sudo edex setup

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for awips: 

thank you

**Comment by srcarter3** [comment]
Hi there,

There is no password for the awips user, so the easiest way to switch to that user is to first switch to root and then switch to the user:
```
sudo su - root
sudo su - awips
```
Thanks.
