### ISSUE TITLE
logfile date inconsistency 

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#4]
past 00 Z some logs write to date UTC while other still write to date local. %d{yyyyMMdd} behaves differently with ingest JVM vs ingestGrib JVM.

**Comment by semmerson** [comment]
Michael,

If version 5 or later of rsyslog(8) is being used, then you might have to
use templates in order to ensure that all times are in UTC.

More information and examples can be found by googling "rsyslog template
UTC".

Regards,
Steve Emmerson
