### ISSUE TITLE
rsync isn't always installed by default

### ISSUE THREAD

**Issue by NaderCHASER** [Unidata/awips2#410]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue
18.2.1-3
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
CentOS 7
* a description of the issue with the steps needed to reproduce it
Run `./awips-install.sh`

There needs to be some sort of check for these utilities. Not all builds of CentOS 7 actually have the binaries installed by default.

Last time it was `wget` and now it's `rsync`.  `whereis(1)` should likely be run first to confirm existence.

Also to that end, `wget` and `rsync` should be pre-requisites in the yum packages if they're going to be used.

**Comment by tiffanycmeyer13** [comment]
`wget` and `rsync` are now installed if they aren't currently existing with the latest `awips_install.sh`
