### ISSUE TITLE
CAVE fails to initialize on Windows 10

### ISSUE THREAD

**Issue by goedeTDS** [Unidata/awips2#425]
I've installed AWIPS II CAVE release 18.2.1-3 following the standard tutorial for Windows (https://unidata.github.io/awips2/install/install-cave/)

Everything went smoothly. However, when I start CAVE I receive an error message stating that the Spring did not initialize correctly and must be shut down. I tried reinstalling it from scratch following these steps agains, but the problem persists.

I'm not sure what to do.

Thanks,

**Comment by srcarter3** [comment]
Hi there, I'm sorry to hear it's not starting up properly.  Could you possibly provide a screenshot of the error dialog that pops up?
Thanks.

**Comment by goedeTDS** [comment]
Hi carter. Thanks for the fast reply.

Below is a screenshot:

![image](https://user-images.githubusercontent.com/45019823/154123584-65cdc232-1913-419a-b7fa-cd10ad405740.png)

**Comment by tiffanycmeyer13** [comment]
Hello,

Do you get this pop-up first before the error? What happens if you click validate?

![image](https://user-images.githubusercontent.com/65614396/154129893-21535435-e081-40d3-807b-144c20c785e4.png)

**Comment by goedeTDS** [comment]
Unfortunately, I get the error before this window pops up.

**Comment by tiffanycmeyer13** [comment]
Hmmm, we haven't had anyone else notice this issue. Can you share what is in your caveData directory and maybe your system variables? 

Also, one more question - can you copy the text from the command terminal and paste that here?

**Comment by goedeTDS** [comment]
caveData only has the .metadata folder which is empty.

System variables are as shown below. Unfortunaly my system is in portuguese, but I can translate it to you if needed.

![image](https://user-images.githubusercontent.com/45019823/154154281-c2b26c4a-361f-4936-bb26-926319ea3587.png)
![image](https://user-images.githubusercontent.com/45019823/154154335-4953e267-4c53-46a6-af68-d26a81b632f3.png)
![image](https://user-images.githubusercontent.com/45019823/154154384-da384fec-e7cc-4ad4-80a7-e2663d6cc18e.png)
![image](https://user-images.githubusercontent.com/45019823/154154420-ef40f188-0392-4efb-8696-c37287d0ebc2.png)

I tried to copy all the output from the terminal to a .txt file that is attached below, 

[cave_terminal_output.txt](https://github.com/Unidata/awips2/files/8074943/cave_terminal_output.txt)

**Comment by srcarter3** [comment]
Hi there, that output text file was helpful. Thank you.
Could you possibly send us this file:
`/C:/Program Files (x86)/UCAR Unidata/AWIPS CAVE/plugins/com.raytheon.uf.viz.core_1.16.1.202112281227/res/spring/viz.xml`

**Comment by srcarter3** [comment]
And just to verify, you do actually have the following path on your system:
`C:\ProgramFiles\Java\jdk1.8.0_181`?

**Comment by goedeTDS** [comment]
Yes, the jdk path is set as highlighted 
![image](https://user-images.githubusercontent.com/45019823/154160292-2f87923d-a545-4d73-a559-3c2c028793ae.png)

below is the .xml file.
https://drive.google.com/file/d/1BL_iJsudCxAGQ1efEKKDM3piu1-XOeCp/view?usp=sharing

**Comment by goedeTDS** [comment]
Sorry, I forgot to allow the access to anyone with the link. Now your should be able to open it.

**Comment by srcarter3** [comment]
Okay yeah that looks the same.
And my original question about the jdk (not your system variables), is that that location **actually exists**, right?  Like when you downloaded our jdk, that's where it saved to?

**Comment by goedeTDS** [comment]
Oh, my mistake, but yes

`C:\Program Files\Java\jdk1.8.0_181`
![image](https://user-images.githubusercontent.com/45019823/154163739-673297bc-50fc-40ca-a15f-a01bbbb19e97.png)

**Comment by srcarter3** [comment]
Okay, I see.
It is interesting that in your screenshot there, the finder lists the path in Portuguese, but in your variable settings, it's in English.  But that looks to be the case for all of your system variables.

One quick question, is it possible to switch your OS to use English temporarily? Or is that a complex thing that would break other programs, etc?

**Comment by goedeTDS** [comment]
Ok, that did it. Now I must get used to the American keyboard pattern haha.

Thanks a lot

**Comment by srcarter3** [comment]
I'm glad that worked, I'm sorry there isn't a better way to have it work in your native language though.

**Comment by srcarter3** [comment]
@Soudaaa One other solution that might be useful for you: 
- You could run a virtual machine and use our packaged Linux Cave for Windows [found here in our documentation](http://unidata.github.io/awips2/install/install-cave/#method-1-linux-virtual-machine)
- Also, if you download VMWare Player, you could maybe install a fresh windows build (in english) and then do the direct installation inside the VM.  That way you're still working in Windows instead of Linux

Both of those solutions *shouldn't* require you to change your entire system language from Portuguese to English though, which might be ideal?

**Comment by goedeTDS** [comment]
Hi @srcarter3. 

To be honest, I'm fine with English as the standard language on my OS, and I managed to set my keyboard back to the portuguese standard. 

Thanks for the additional insights.
