### ISSUE TITLE
Failed to launch cave

### ISSUE THREAD

**Issue by AlexanderBallbach** [Unidata/awips2#442]
![unknown](https://user-images.githubusercontent.com/62922478/161164253-44aee688-a0ff-4874-af89-16fcefc1c326.png)
![image](https://user-images.githubusercontent.com/62922478/161164331-94c8dffd-73d7-4b14-a882-e5860fcf50b5.png)

**Comment by tiffanycmeyer13** [comment]
Sorry you are having some issues. Couple questions:

-Do you have the latest version of CAVE installed along with the correct versions of python and java? (http://unidata.github.io/awips2/install/install-cave/#method-2-direct-windows-install)
-Can you send us a screencapture of your system variables
-What language is your Windows OS using?
