### ISSUE TITLE
Maps Only Occupy Lower Left Quadrant of Pane

### ISSUE THREAD

**Issue by airbusman5514** [Unidata/awips2#490]
Title says it all. See attached screenshot.

Specs:
Windows 11 x64
All required pre-requisites per Unidata install guide
Intel i5 evo integrated graphics

![image](https://user-images.githubusercontent.com/28398677/193469135-6493c49e-839c-4114-b727-addafd6dc586.png)

**Comment by tiffanycmeyer13** [comment]
Try following these steps to fix your issue:

- Right-click on the CAVE.exe (or shortcut) icon, select Properties
- Select the Compatibility tab
- Click "Change High DPI Settings"
- At the bottom enable "Override High DPI scaling behavior"
- Change the dropdown from Application to System
