### ISSUE TITLE
Error instantiating workbench: null

### ISSUE THREAD

**Issue by airbusman5514** [Unidata/awips2#492]
Running under Windows 11 with a discrete graphics card, I get this issue when trying to start CAVE.

![image](https://user-images.githubusercontent.com/28398677/195237715-3cc17626-35dc-4c88-a41f-c7759abdac8c.png)

System specs:
Windows 11
NVIDIA GeForce RTX 3070 Ti
Intel i9-10900K processor
64GB DDR4 RAM

I'm guessing I installed one of the pre-requisites incorrectly, but without a foundation in computer science, I wouldn't know where to look.

Thanks in advance!

**Comment by srcarter3** [comment]
Fortunately, this error is not associated with the complicated pre-req installation for Windows. It actually has to do with the IP settings on the computer.

Please see our documentation for the steps to get around this issue:
http://unidata.github.io/awips2/appendix/common-problems/#windows-cave-start-up-error
