### ISSUE TITLE
Fuzzy Text

### ISSUE THREAD

**Issue by airbusman5514** [Unidata/awips2#498]
While it's not a critical issue, on my system the text on buttons and menus appears fuzzy, which can make it hard to read when I'm working with CAVE. Is there a fix for this? If it's tied to the corner map display issue, it's no big deal.

**Comment by srcarter3** [comment]
Can you post a screenshot showing this issue you describe please?
And which Operating System are you using and which installation method of CAVE?
Thanks.

**Comment by airbusman5514** [comment]
Apologies, here it is. Notice the difference between CAVE D2D - MOB at the top and the menu/button text in the window.

![image](https://user-images.githubusercontent.com/28398677/207663349-352e923b-6d78-4d32-abd1-097be6952a6c.png)


I'm using Windows 11 with the long method of installation.

**Comment by srcarter3** [comment]
Hmm.  We don't currently have a Windows11 machine to test with.
On Windows 10 the two text areas (very top bar vs CAVE application text -- menus/buttons) look much more similar in thickness:

![image](https://user-images.githubusercontent.com/21114460/207671150-83376d2a-a2ef-4bfd-9a0a-83a08ca53a9a.png)

The text at the top is set by your OS and the text within CAVE is set in Java and then rendered via your OS.  The fonts and sizes/thicknesses are slightly different.   My only suggestion might be to try playing with some of the Windows Display settings to see if you could change the resolution or size of the screen or applications.
Sorry I don't have a better solution at the moment.

**Comment by airbusman5514** [comment]
No worries. Hopefully with the AWIPS v20 update things will jive better with newer machines.
