### ISSUE TITLE
Incorporate LDM version 6.14.3 into the next official release

### ISSUE THREAD

**Issue by sebenste** [Unidata/awips2#500]
Current included version with AWIPS-2 is 6.13.16. There are significant bug fixes in 6.14.3 that are making it worth adding to the next release.

**Comment by srcarter3** [comment]
Hi there, we are currently actively working on converting v20 to a Unidata AWIPS build.  We don't plan on releasing an EDEX of v20 right away, but once we get to that revision we can make sure to have at least this version of LDM incorporated.

At this time, I don't think we will make any more releases for v18, unless there is something absolutely critical.
Do you know what bugs this version of LDM addresses that relate to AWIPS?
Thanks.

**Comment by sebenste** [comment]
Hello,

The biggest one would be files not closing properly, although this was more of a problem in 6.13.17. Also, the documentation has been substantially updated.

Knowing that you are going to have your next release as version 20, I will defer this request until that release.

Issue closed.
