### ISSUE TITLE
Issue with exporting .cmap

### ISSUE THREAD

**Issue by Firefighter14141** [Unidata/awips2#531]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
* a description of the issue with the steps needed to reproduce it

If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

**Comment by Firefighter14141** [comment]
Hey I noticed a small quirk when trying to import a .cmap into version 20 from older versions. The RGBA formatting is all backwards which results in an import error. I was able to correct this by just changing the order of the columns in Excel, but wanted to let you guys know. Here's an example. 

Instead of R,G,B,A the older version exports as A,B,G,R which when imported into Version 20 will cause an import error. 

![Cmap-import-issue](https://user-images.githubusercontent.com/54453523/232880193-78ad4014-2c54-4a2c-b65b-2dc369c2e603.jpg)

**Comment by tiffanycmeyer13** [comment]
Hello,

Thank you for notifying us of this. This is a difference between versions of AWIPS and is good to take note of.

Thank you!

**Comment by srcarter3** [comment]
Just to add on, as we have also mentioned in our documentation, there is no guarantee for any compatibility between major versions of AWIPS (ie. between 18 and 20, etc).  So, while this is good to know about, and we're glad you have a way to make it conform with what v20 expects, this is not a bug, or something we will address.  Sorry for the inconvenience.
