### ISSUE TITLE
Windows 11 Launch Error. Cannot find 'C\Users\   '

### ISSUE THREAD

**Issue by ArloG3300** [Unidata/awips2#538]
Using the .msi installer on a newly formatted Windows 11 pc.
Installs good. Error on launching. My main user account/login is the first initial of my name with a period. A space and my last name.
As you can see, apparently the application needs a user with no spaces.

I have tried uninstalling awips-cave. Then because Win 11 does no natively allow installing an .msi as administrator.
I performed a few registry edits to allow it. Installed as administrator. Same error.
I have not enabled the Adminitsrator account as of yet waiting any suggestions as to a fix.

Under the previous method this application was working well.

![awips_cave_error](https://user-images.githubusercontent.com/75093499/236348331-6f153993-c484-443c-8360-8dea4b6cd644.png)

**Comment by tiffanycmeyer13** [comment]
Hello,

Sorry you ran into this issue. We will fix this in future releases. In the meantime, you can make the following change and it should work with CAVE installed at the user level.

Open the CAVE shortcut on your desktop with a text editor. Remove the last line and replace with:

`cd "%APPDATA%\UCAR Unidata\AWIPS CAVE"`
`start CAVE.exe`

Let us know if that worked for you.
