### ISSUE TITLE
ECMWF total precipitation not loaded

### ISSUE THREAD

**Issue by GarryLai** [Unidata/awips2#662]
I have noticed bottom of https://www.unidata.ucar.edu/blogs/news/entry/awips-tips-adding-ecmwf-data, but I still not figure out how to fix it.
I replace 193 with `193:193:Total precipitation:m:APCP:TP` in `/awips2/edex/data/utility/common_static/base/grib/tables/98/0/4.2.0.1.table` and then restart EDEX, but it still not working in new files.

**Comment by srcarter3** [comment]
Hi there,

Can you try with either `APCPN` or `TP` like the following:

`193:193:Total precipitation:m:APCPN`
`193:193:Total precipitation:m:TP`

Can you let me know any of those fixes the problem?

Also, if you could look at the `/awips2/edex/logs/edex-ingestGrib-20240209.log` and see if there's any output in there when trying to manually ingest a ECMWF file, that could be helpful?

Thanks.

**Comment by GarryLai** [comment]
> Hi there,
> 
> Can you try with either `APCPN` or `TP` like the following:
> 
> `193:193:Total precipitation:m:APCPN` `193:193:Total precipitation:m:TP`
> 
> Can you let me know any of those fixes the problem?
> 
> Also, if you could look at the `/awips2/edex/logs/edex-ingestGrib-20240209.log` and see if there's any output in there when trying to manually ingest a ECMWF file, that could be helpful?
> 
> Thanks.

It seems that didn`t help.

**Comment by srcarter3** [comment]
Can you please try again today and post the `/awips2/edex/logs/edex-ingestGrib-20240212.log` file?

**Comment by chungyi886** [comment]
Simply replaced “193:193:Total precipitation:m:ECMWFTP” in /awips2/edex/data/utility/common_static/base/grib/tables/98/0/4.2.0.1.table and then restarted EDEX. After feeding the ecmwf grib2  files,the edex server got the new parameter ECMWFTP . Next step is adding a new derivative parameter TPA which is ECMWFTP   value multiplied by 1000 and assigned its unit is mm. I hope this answers your question.

**Comment by GarryLai** [comment]
> Simply replaced “193:193:Total precipitation:m:ECMWFTP” in /awips2/edex/data/utility/common_static/base/grib/tables/98/0/4.2.0.1.table and then restarted EDEX. After feeding the ecmwf grib2 files,the edex server got the new parameter ECMWFTP . Next step is adding a new derivative parameter TPA which is ECMWFTP value multiplied by 1000 and assigned its unit is mm. I hope this answers your question.

How can I add a derivative parameter?

**Comment by chungyi886** [comment]
Derived parameters definitions are in the directory /awips2/edex/data/utility/common_static/base/derivedParameters/definitions . 

Try to add a new parameter TPA.xml : 
<DerivedParameter unit="mm" name="Total precipitation Accumulation” abbreviation="TPA">
...
[TPA.xml.txt](https://github.com/Unidata/awips2/files/14261958/TPA.xml.txt)

**Comment by srcarter3** [comment]
@GarryLai Are you using the same input file to test your changes?
EDEX won't process duplicate entries unless you clean out the database and `hdf5/` directory.  I think it's easier to use different files when testing, because of this.

**Comment by GarryLai** [comment]
I find the way!
What I need is add these two lines in `/awips2/edex/data/utility/common_static/base/grib/tables/98/0/4.2.0.1.table`
```
8:8:Missing
193:193:Total precipitation:m:APCP:TP
```
The reason is that "TP" was assigned to ID 8 in `/awips2/edex/data/utility/common_static/base/grib/tables/-1/-1/4.2.0.1.table`.
So we need to override this.

In the same way, add these two lines in `/awips2/edex/data/utility/common_static/base/grib/tables/98/0/4.2.2.0.table`
```
5:5:Missing
201:201:Water runoff:m:WATR
```

Thanks for everyone's helping!
