### ISSUE TITLE
CentOS-7 End of Life

### ISSUE THREAD

**Issue by anikfal** [Unidata/awips2#691]
After June 30, 2024 which is the EOL of CentOS-7, what are we supposed to do for the installation of AWIPS? Should we keep using CentOS-7, or can we migrate to other OS?

**Comment by tiffanycmeyer13** [comment]
We will be using Rocky8 for our next release. We will have a CAVE release out tomorrow to connect to our public EDEX.

However, the National Weather Service is still working on their 23.4.1 release to operations. In the interim, we are waiting on final clearance from the NWS before releasing a public Unidata EDEX install and source code. We understand the CentOS7/RHEL7 end of life is upon us, but this is all we are allowed to provide at this time.

**Comment by anikfal** [comment]
May I know if the type/version of Linux matters in case of using Docker for installation?

**Comment by a5ehren** [comment]
If running in Docker, the base OS should not matter.

**Comment by a5ehren** [comment]
@tiffanycmeyer13 are you able to release the v23 source for the non-EDEX parts of AWIPS?

**Comment by tiffanycmeyer13** [comment]
> @tiffanycmeyer13 are you able to release the v23 source for the non-EDEX parts of AWIPS?

At this point we are not able release any source code for this version of AWIPS. Once we get the OK from NWS we will.

**Comment by tiffanycmeyer13** [comment]
> May I know if the type/version of Linux matters in case of using Docker for installation?

CAVE is designed for RHEL8 flavors of Linux (including Rocky)
