### ISSUE TITLE
`edex start` asks for a password

### ISSUE THREAD

**Issue by anikfal** [Unidata/awips2#694]
I had to set a password for the `awips` user, since it asks me for a password every time I run `su - awips`.
Now when I run `edex start`, it asks for a password again, but the password I made for the `awips` user is not correct for it.

**Comment by tiffanycmeyer13** [comment]
Can you provide more information? 

What version of AWIPS are you running? 
Are you running EDEX on a your own Virtual Machine/hardware or a Unidata downloaded virtual machine?

**Comment by anikfal** [comment]
I am running EDEX on my own Virtual Machine.

I followed the instructions on this [page](http://unidata.github.io/awips2/) and installed it by using `awips_install.sh`.
I can check the version of AWIPS, but the OS is CentOS7.

**Comment by tiffanycmeyer13** [comment]
You need `sudo` to run/start EDEX.

If you are `awips` user - then run `sudo edex start`
If you are `root`, then run `edex start`

Please note that the data needed to feed your own EDEX is not publicly available and you will need your own access to an LDM or datafeed.
