### ISSUE TITLE
No result after running `cave`

### ISSUE THREAD

**Issue by anikfal** [Unidata/awips2#695]
After running `cave` on CentOS7, nothing happens. What am I supposed to expect after running `cave`? I couldn't figure it out by reading the documentation (http://unidata.github.io/awips2/install/install-cave/).

May I know if there is any _getting_started_ guide showing some examples as steps to do after installing EDEX and CAVE?

**Comment by srcarter3** [comment]
Hi there, after running `cave` on the command line after installing from our install script (`awips_install.sh`), you should soon be prompted with the EDEX Connection Window, shown here [in our documentation here](https://unidata.github.io/awips2/install/install-cave/#edex-connection).

**Comment by anikfal** [comment]
Actually even after half an hour, no EDEX Connection Window is prompted after running `cave`. Is it a matter of X11 forwarding? I connect to the VM via SSH. So does this mean that everybody is supposed to install CAVE on their own local machine and then connect to EDEX?

I wonder if CAVE could be accessed by a web browser in any OS.

**Comment by tiffanycmeyer13** [comment]
CAVE is very dependent on graphics so it is not available in a web browser and as stated in our [documentation](https://unidata.github.io/awips2/install/install-cave/#general-requirements) is not supported to run through X11 forwarding

We also have a[ Virtual Machine with CAVE](https://unidata.github.io/awips2/install/install-cave/#method-2-linux-virtual-machine) already installed if you want to connect to our public EDEX

**Comment by srcarter3** [comment]
Remotely accessing CAVE is documented in our known issues here:
https://unidata.github.io/awips2/appendix/common-problems/#remotely-connecting-to-cave

It is highly problematic and the only method we can recommend is using VNC.

This is why we have created so many installation options with direct installs for Windows, Linux and Mac, as well as the virtual machine option already mentioned by Tiffany.

**Comment by anikfal** [comment]
Some errors in the log file `/home/awips/caveData/logs/consoleLogs/detectdms/cave_20240704_084151_pid_4251_console.log`:
```
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
        no swt-pi4-gtk-4936r26 in java.library.path: [/awips2/java/lib, /awips2/python/lib, /awips2/python/lib/python3.6/site-packages/jep, /awips2/ldm/lib, /awips2/qpid/lib, /awips2/yajsw/lib, /awips2/psql/lib, /awips2/postgresql/lib, /awips2/python/lib, ., /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
        no swt-pi4-gtk in java.library.path: [/awips2/java/lib, /awips2/python/lib, /awips2/python/lib/python3.6/site-packages/jep, /awips2/ldm/lib, /awips2/qpid/lib, /awips2/yajsw/lib, /awips2/psql/lib, /awips2/postgresql/lib, /awips2/python/lib, ., /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
        Can't load library: /home/awips/.swt/lib/linux/x86_64/libswt-pi4-gtk-4936r26.so
        Can't load library: /home/awips/.swt/lib/linux/x86_64/libswt-pi4-gtk.so
```
So the SWT library is not installed by `awips_install.sh`? Am I supposed to install it myself?

**Comment by anikfal** [comment]
> So the SWT library is not installed by `awips_install.sh`? Am I supposed to install it myself?

I handled this error by installing `gtk3`. But another problem occurred:
```
...
!ENTRY org.eclipse.osgi 4 0 2024-07-04 14:21:18.176
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
      at org.eclipse.swt.SWT.error(SWT.java:4895)
      ...
```

**Comment by anikfal** [comment]
CAVE could be eventually loaded by the VM, and I entered `edex-cloud.unidata.ucar.edu`. However, it was very slow as expected, with loading in progress. And also no _File->New Map_ could be displayed.
Anyway, I may try a VNC instead of SSH.

May I know if setting up EDEX without CAVE can be an option?

**Comment by srcarter3** [comment]
As stated before, ssh-ing to access CAVE is known to be problematic. It is not something we support.

> May I know if setting up EDEX without CAVE can be an option?

Yes, EDEX and CAVE are two independent, stand-alone pieces of software. CAVE is the graphical interface application used to view and analyze data. EDEX is the backend server used to ingest, decode, store, and serve that data
