### ISSUE TITLE
`ldmadmin` is not running after `service edex_ldm start`

### ISSUE THREAD

**Issue by anikfal** [Unidata/awips2#699]
LDM seems to be started successfully:
```
[awips@detectdms ~]$ sudo service edex_ldm start
Starting edex_ldm (via systemctl):                         [  OK  ]
```
However, the EDEX status shows `ldmadmin` as not running:
```
[awips@detectdms ~]$ edex
[edex status]
 postgres    :: running :: pid 5107
 pypies      :: running :: pid 5194
 qpid        :: running :: pid 5240
 EDEXingest  :: running :: pid 6057 20025
 EDEXgrib    :: running :: pid 6133 20034
 EDEXrequest :: running :: pid 6194 20042
 ldmadmin    :: not running
```

**Comment by tiffanycmeyer13** [comment]
Open a new terminal and as the `awips` user try running `ldmadmin start` and let us know what errors you are seeing. 

Do you have an LDM server that is pushing data to you?

**Comment by anikfal** [comment]
`ldmadmin` is actually not available by the `awips` user. I thought it would be installed by `./awips_install.sh --edex`.
So I will follow the documentations to install LDM.

**Comment by tiffanycmeyer13** [comment]
I suggest looking at your install because LDM should be installed in /awips2/ldm

**Comment by anikfal** [comment]
Here are the contents of the directory `/awips2/ldm/`:
`ldm-6.14.5  ldm-6.14.5.tar.gz  SOURCES`

And the contents of the directory `/awips2/ldm/ldm-6.14.5/src`:
```
acinclude.m4  configure            ensureSyslogEntry  grib2          ldmsend      misc      pqcopy    pqsend     registry        test
aclocal.m4    configure.ac         ensureVar          gribinsert     ldm.spec.in  noaaport  pqcreate  pqsurf     regutil         TODO
AUTHORS       COPYRIGHT            extractDecls       html           lib          notifyme  pqexpire  pqutil     rpc             uldbutil
BACKLOG       delayQueue           fauxPq             hupsyslog      log          pq        pqing     protocol   rpmUserActions  ulogger
build-aux     ensureLdmhomeLinks   feedme             ldm-50x50.xpm  m4           pqact     pqinglib  protocol2  rtstats
CHANGE_LOG    ensureRpcEntry       fileIngest         ldmd           Makefile.am  pqcat     pqinsert  README     scour
config.h.in   ensureServicesEntry  gempak             ldmping        Makefile.in  pqcheck   pqmon     regex      scripts
```
However, `ldmadmin` is listed as not running after starting EDEX:
```
[awips@detectdms src]$ edex

[edex status]
 postgres    :: running :: pid 1528
 pypies      :: running :: pid 1615
 qpid        :: running :: pid 1661
 EDEXingest  :: running :: pid 2455 4776
 EDEXgrib    :: running :: pid 2352 4785
 EDEXrequest :: running :: pid 2401 4793
 ldmadmin    :: not running
```

**Comment by anikfal** [comment]
According to the [docs](http://unidata.github.io/awips2/install/install-edex/), two locations below must be there. But they are not available:
> /awips2/ldm/etc - Location of ldmd.conf and pqact.conf
> /awips2/ldm/logs - LDM logs

Although the `/awips2/ldm` directory has been created:
```
[awips@detectdms ldm]$ ls
ldm-6.14.5  ldm-6.14.5.tar.gz  SOURCES
```

The path to `ldmd.conf` is `/awips2/ldm/ldm-6.14.5/src/ldmd/ldmd.conf`

**Comment by anikfal** [comment]
I reinstalled EDEX and according to [awips-install.log](https://github.com/user-attachments/files/16158480/awips-install.log), there are some issues with the LDM rpm package:
```
Installing : awips2-ldm-20.3.2-6.14.5.2.el7.x86_64                     49/145
/var/tmp/rpm-tmp.NKULzr: line 32: patch: command not found
warning: %post(awips2-ldm-20.3.2-6.14.5.2.el7.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package awips2-ldm-20.3.2-6.14.5.2.el7.x86_64
```
After completing the installation there is an error message as below:
```
...
Complete!
sed: can't read /awips2/ldm/etc/registry.xml: No such file or directory
EDEX server has finished installing, the install log can be found in /tmp/awips-install.log
```
LDM is apparently not installed and its directories are not there:
```
[centos@detectdms ~]$ cd /awips2/ldm/
[centos@detectdms ldm]$ ls
ldm-6.14.5  ldm-6.14.5.tar.gz  SOURCES
```

May I know if I install LDM manually, can I get it connected to the EDEX server? LDM must be installed by a different user (`ldm`) in case of manual installation, while EDEX is run with the `awips` user. This is not problematic?  I couldn't find any guidance in the [docs](https://docs.unidata.ucar.edu/ldm/current/basics/index.html) discussing this issue.

**Comment by tiffanycmeyer13** [comment]
As you can see from the initial installation of LDM it was failing to install because it could not find the `patch` command, which likely would mean it doesn't matter how you install it, LDM will fail without the `patch` command available.

I suggest installing patch (`sudo yum install patch`) and re-installing EDEX (I'm not sure if you are running a "minimal centos7" cloud server, but most default centos servers already have patch installed which is why we have never had anyone run into this issue before)

**Comment by anikfal** [comment]
After installing `patch`, some other problems occurred:
```
...
  Installing : awips2-python-tables-3.5.1-3.6.15.1.16.2.1.el7.x86_64     48/145
  Installing : awips2-ldm-20.3.2-6.14.5.2.el7.x86_64                     49/145
patching file pqact/filel.c
[awips-install.log](https://github.com/user-attachments/files/16173918/awips-install.log)

Hunk #1 succeeded at 1288 (offset 2 lines).
Hunk #2 succeeded at 1340 with fuzz 1 (offset 12 lines).
patching file pqact/pqact.c
Hunk #1 succeeded at 269 (offset 11 lines).
Hunk #2 succeeded at 293 (offset 11 lines).
Hunk #3 succeeded at 332 (offset 9 lines).
Hunk #4 succeeded at 342 (offset 9 lines).
Hunk #5 succeeded at 394 (offset 9 lines).
Hunk #6 succeeded at 424 with fuzz 1 (offset 8 lines).
FATAL: ldm configure has failed!
warning: %post(awips2-ldm-20.3.2-6.14.5.2.el7.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package awips2-ldm-20.3.2-6.14.5.2.el7.x86_64
  Installing : awips2-python-matplotlib-2.2.4-3.6.15.1.16.2.1.el7.x86    50/145
  Installing : awips2-maps-database-20.3.2-2.noarch                      51/145
...
```
Here's the full log file: [awips-install.log](https://github.com/user-attachments/files/16173932/awips-install.log)

-------
### Preinstallation:
I had to modify yum configs, since due to the EOL of CentOS-7, the previous repos were not available anymore:
```
sudo sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
sudo sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
sudo sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
```
More information:
```
[awips@detectdms ~]$ sudo yum grouplist
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * epel: mirror.freethought-internet.co.uk
Available Environment Groups:
   Minimal Install
   Compute Node
   Infrastructure Server
   File and Print Server
   Cinnamon Desktop
   MATE Desktop
   Basic Web Server
   Virtualization Host
   Server with GUI
   GNOME Desktop
   KDE Plasma Workspaces
   Development and Creative Workstation
Installed Groups:
   awips2-server
Available Groups:
   Cinnamon
   Compatibility Libraries
   Console Internet Tools
   Development Tools
   Educational Software
   Electronic Lab
   Fedora Packager
   General Purpose Desktop
   Graphical Administration Tools
   Haskell
   LXQt Desktop
   Legacy UNIX Compatibility
   MATE
   Milkymist
   Scientific Support
   Security Tools
   Smart Card Support
   System Administration Tools
   System Management
   TurboGears application framework
   Xfce
Done
```
Is it still due to the CentOS-7 minimal installation?

**Comment by anikfal** [comment]
It seems the issue has been resolved.
I replaced the VM with a snapshot of CentOS-7 preinstalled with AWIPS. Now LDM is also running.
