### ISSUE TITLE
Is WarnGen being disabled in 16.1.4?

### ISSUE THREAD

**Issue by live4right** [Unidata/awips2#73]
Hello Michael,

I have been enjoying the AWIPS II CAVE client immensely. I have configured WarnGen more fully for my CWA, I noticed that on the new 16.1.4 plugin.xml on WarnGen it says that you have removed the icon. Does that mean that WarnGen will be disabled now? Thanks

--Carl
   plugin.xml  Warngen remove icon   5 days ago

**Comment by mjames-upc** [comment]
Hi Carl,

The commit that you mention has no consequence for WarnGen other than the icon is removed replaced by a text label.  WarnGen will continue to be available in CAVE.
