### ISSUE TITLE
binLightning and Satellite.Mcidas unable to decode.

### ISSUE THREAD

**Issue by klatteri** [Unidata/awips2#74]
There has been an issue on the most recent Unidata data releases with lightning decoding/ingesting and mcidas decording/ingesting. Logs below. 

--- Lightning Log --- 

[Ingest.textlightning-1] PersistSrv: Critical persistence error occurred.  Individual records that failed will be logged separately.
com.raytheon.uf.common.dataplugin.PluginException: Plugin binlightning is not registered with the PluginRegistry
ERROR 2016-04-26 14:23:18,363 [Ingest.textlightning-1] PersistSrv: Record /binlightning/2016-04-26_14:21:44.778[2016-04-26_14:21:44.778--2016-04-26_14:22:44.562]/2016-04-26_14:21:44.778/2016-04-26_14:22:44.562/USPLN failed persistence due to critical error logged above.

--- Satellite Ingest Log --- 

ERROR 2016-04-27 13:12:17,387 [Ingest.Satellite.Mcidas-1] PersistSrv: Critical persistence error occurred.  Individual records that failed will be logged separately.
ERROR 2016-04-27 13:12:17,387 [Ingest.Satellite.Mcidas-1] PersistSrv: Record /satellite/2016-04-27_12:45:00.0/McIDAS/GOES13/GOES-East-West/Imager Visible/2 failed persistence due to critical error logged above.

**Comment by mjames-upc** [comment]
USPLN and McIDAS are fully supported in the soon-to-be-released 16.1.4 build.
