### ISSUE TITLE
Scriptlet Error on Edex Install

### ISSUE THREAD

**Issue by WxmanJ** [Unidata/awips2#78]
chown root /awips2/ldm/ldm-6.12.14/bin/ldmd
chmod 4755 /awips2/ldm/ldm-6.12.14/bin/ldmd
chown root /awips2/ldm/ldm-6.12.14/bin/hupsyslog
chmod 4755 /awips2/ldm/ldm-6.12.14/bin/hupsyslog
if test -f /awips2/ldm/ldm-6.12.14/bin/noaaportIngester; then \
        chown root /awips2/ldm/ldm-6.12.14/bin/noaaportIngester; \
        chmod 4755 /awips2/ldm/ldm-6.12.14/bin/noaaportIngester; \
    fi
if test -f /awips2/ldm/ldm-6.12.14/bin/dvbs_multicast; then \
        chown root /awips2/ldm/ldm-6.12.14/bin/dvbs_multicast; \
        chmod 4755 /awips2/ldm/ldm-6.12.14/bin/dvbs_multicast; \
    fi
  Installing : awips2-edex-16.1.4-16.x86_64                               13/78 
Starting PostgreSQL As User - awips...
15.1.1 Updating radar table to include volume scan number.
ERROR:  relation "radar" does not exist
CONTEXT:  SQL statement "ALTER TABLE radar ADD COLUMN volumescannumber integer"
PL/pgSQL function inline_code_block line 3 at SQL statement
Radar update not needed. Continuing...
Stopping PostgreSQL As User - awips...
waiting for server to shut down.... done
server stopped
  Installing : awips2-pypies-16.1.4-2.x86_64                              14/78 
  Installing : awips2-edex-gfe-16.1.4-16.x86_64                           15/78 
  Installing : awips2-python-nose-0.11.1-4.noarch                         16/78 
  Installing : awips2-python-numpy-1.8.0-1.x86_64                         17/78 
  Installing : awips2-python-pycairo-1.2.2-3.x86_64                       18/78 
  Installing : awips2-qpid-java-common-0.32-1.el6.noarch                  19/78 
  Installing : awips2-qpid-java-client-0.32-1.el6.noarch                  20/78 
  Installing : awips2-python-pygtk-2.8.6-3.x86_64                         21/78 
  Installing : awips2-python-matplotlib-1.5.1-1.x86_64                    22/78 
  Installing : awips2-python-h5py-1.3.0-5.x86_64                          23/78 
  Installing : awips2-python-pupynere-1.0.13-3.noarch                     24/78 
  Installing : awips2-python-jep-3.4.1-2.x86_64                           25/78Non-fatal POSTIN scriptlet failure in rpm package awips2-python-jep-3.4.1-2.x86_64

ln: creating symbolic link `/awips2/python/lib/libjep.so': File exists
warning: %post(awips2-python-jep-3.4.1-2.x86_64) scriptlet failed, exit status 1
  Installing : awips2-python-scipy-16.1.4-0.9.0.1.x86_64                  26/78 
  Installing : awips2-gfesuite-server-15.1.2-5.noarch                     27/78 
  Installing : awips2-httpd-pypies-2.2.15-15.15.x86_64                    28/78 
  Installing : awips2-common-base-16.1.4-16.x86_64                        29/78 
  Installing : awips2-notification-16.1.4-15.x86_64                       30/78 
  Installing : awips2-qpid-java-broker-0.32-2.el6.noarch                  31/78 
  Installing : awips2-ncep-database-16.1.4-2.noarch                       32/78

**Comment by mjames-upc** [comment]
It's a non-fatal rpm scriptlet error, and had been fixed in the recent 16.1.5 build.
