### ISSUE TITLE
Error When Starting Cave

### ISSUE THREAD

**Issue by WxmanJ** [Unidata/awips2#79]
[awips@localhost ~]$ /awips2/cave/cave.sh 
Calling getTestMode()
Can't open .logPref or ~/.logPref; using defaults.
getTestMode() returned OPERATIONAL
Cleaning consoleLogs: 
find /home/awips/caveData/logs/consoleLogs -type f -name *.log -mtime +30 -exec rm {} \;
find: `/local/cave-eclipse/': No such file or directory
mktemp: failed to create directory via template`/local/cave-eclipse/localhost.localdomain-awips-XXXX': No such file or directory

Startup Error:
CAVE's Spring Container did not initialize correctly and CAVE must shut down. Attempt to restart CAVE?

**Comment by mjames-upc** [comment]
Fixed in the current release 16.1.5 linux client.
