### ISSUE TITLE
GFESuite requiring numpy

### ISSUE THREAD

**Issue by klatteri** [Unidata/awips2#93]
GFESuite fails to activate until numpy is installed through the normal python repositories. 

INFO  2016-12-08 06:29:45,625 [EDEXMain] Executor: Waiting for async startup dependencies to complete...

INFO  2016-12-08 06:29:54,294 [pool-2-thread-1] GFESiteActivation: EDEX - Activation task in progress by another EDEX instance.  Waiting..

After doing "yum install numpy" EDEX started without issue

**Comment by KeithLatteri** [comment]
Continued.. After doing "yum install numpy" EDEX started without issue
