### ISSUE TITLE
5-Pane Layout option missing on Mac D2D

### ISSUE THREAD

**Issue by jaredwsmith** [Unidata/awips2#94]
In CAVE 16.2.2 on macOS Sierra and OS X El Capitan, I'm no longer able to select the 5-pane option for D2D from the View menu. I checked to ensure it was not removed from the Linux version and it is still available there, so it looks like this was an omission or issue from the Mac side.

**Comment by mjames-upc** [comment]
Hi Jared, the 5-pane toggle is unavailable due to an outstanding OpenGL issue on Mac.  Hopefully will be worked on for the next release.
