### ISSUE TITLE
jspawnhelper in the cave application bundle on Mac is not executable

### ISSUE THREAD

**Issue by jaredwsmith** [Unidata/awips2#95]
When trying to set up PyDev in an effort to get derived parameters working, I repeatedly got the message that spawning the Python interpreter failed.

I did some digging and found that this issue can creep up if jspawnhelper is not executable for whatever reason. Here is an answer from another Java project that led me down the right path: http://stackoverflow.com/a/31015371

Sure enough, this ended up being the problem. After manually making jspawnhelper within the Mac application bundle executable, I'm able to add Python interpreters as needed.

**Comment by live4right** [comment]
Hey Jared,
Is there a similar component on the Windows version too? I have been trying to get the PyDev to point to my Python installation so I can get at least the wind data (barbs, streamlines) to display, but it hasn't worked out too well. It goes through 1,836 lines of code and it acts like the python isn't there.  Let me know if you can get those derived parameters figured out for the Windows version if you have the time and let me know how to set things up right. Thanks

--Carl

**Comment by mjames-upc** [comment]
Thanks for letting me know about this, Jared, I'll look at it shortly.

**Comment by jaredwsmith** [comment]
Still seeing this in 17.1.1 when I set up PyDev or work with localizations, just FYI. Same steps fix it with the new app bundle.

**Comment by mjames-upc** [comment]
Known issue being addressed for 17.1.1-2
