### ISSUE TITLE
Yum issue with Python 2.7.10

### ISSUE THREAD

**Issue by WxmanJ** [Unidata/awips2#97]
Installing the latest iteration of EDEX (16.2.3) also installs Python 2.7.10. This version of python does not appear to be compatible with yum. Upon installing EDEX, yum is no longer usable and provides an error. Removing the python installation rpm makes yum once again functional.

Here is the error received. 

```
There was a problem importing one of the Python modules
required to run yum. The error leading to this problem was:

No module named yum
```

**Comment by mjames-upc** [comment]
Unidata does not support 16.2.3, but I believe what will fix this for you is 
```
export LD_LIBRARY_PATH=/usr/lib:/lib:/usr/lib64:/lib64
```

followed by yum install again.

**Comment by WxmanJ** [comment]
I meant to say 16.2.2-3.

**Comment by WxmanJ** [comment]
This did fix the issue. Thank you, Michael.
