### ISSUE TITLE
EdexBridge Issue in LDM

### ISSUE THREAD

**Issue by WxmanJ** [Unidata/awips2#98]
After running the EDEX install under CentOS 7, an issue occurred when starting the LDM process that made the edexBridge unusable from the ldmd.conf line, `EXEC "edexBridge -s localhost"`. This particular line would invoke a child status error 127. When trying to run edexBridge by itself and isolate the error, the following message was given as output `libboost_program_options-mt.so.1.53.0: cannot open shared object file: No such file or directory.` This library was later installed and edexBridge was once again working properly again when starting the LDM.

**Comment by mjames-upc** [comment]
Check what is returned from the command `ldd /awips2/ldm/bin/edexBridge` and see if you are missing shared libraries.

You may want to try the Unidata el7 binary build of edexBridge available at https://github.com/Unidata/awips2/raw/unidata_16.2.2-el7/rpms/awips2.upc/Installer.ldm/patch/bin/edexBridge

**Comment by WxmanJ** [comment]
The shared library was indeed missing. After installing it, edexBridge did work correctly.

**Comment by mjames-upc** [comment]
@WxmanJ what shared library was missing?

**Comment by WxmanJ** [comment]
libboost_program_options-mt.so.1.53.0
